# Generated by Django 5.0.2 on 2024-03-25 15:25

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=martor.models.MartorField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.URLField(max_length=100),
        ),
    ]
