# Generated by Django 5.0.2 on 2024-03-28 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_jobbookmarks_job_remove_jobbookmarks_user_and_more'),
        ('jobs', '0002_alter_job_description_alter_job_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobBookMarks',
            new_name='JobBookmark',
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.company'),
        ),
    ]
