# Generated by Django 5.0.2 on 2024-04-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_job_instructions_job_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="contact_info",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="requirements",
            field=models.CharField(default="no reqs", max_length=500),
            preserve_default=False,
        ),
    ]
