# Generated by Django 5.0.2 on 2024-04-16 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="applied_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
