# Generated by Django 5.0.2 on 2024-04-16 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_jobapplication_applied_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="applied_time",
            new_name="applied_date",
        ),
    ]
