# Generated by Django 5.0.2 on 2024-04-17 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0009_alter_jobapplication_applied_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="tag",
            new_name="keywords",
        ),
        migrations.AddField(
            model_name="job",
            name="additional",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="deadline",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="holland",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="information",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="job_fields",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="mbti",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="overview",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
