# Generated by Django 5.0.2 on 2024-04-17 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0010_rename_tag_job_keywords_job_additional_job_deadline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="information",
        ),
    ]
