# Generated by Django 5.0.2 on 2024-04-17 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0011_remove_job_information"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobbookmark",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="jobs.job"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobbookmark",
            constraint=models.UniqueConstraint(
                fields=("user", "job"), name="bconstraint"
            ),
        ),
    ]
