# Generated by Django 5.0.2 on 2024-04-17 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0012_alter_jobbookmark_job_jobbookmark_bconstraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.UniqueConstraint(
                fields=("user", "job"), name="jaconstraint"
            ),
        ),
    ]
