# Generated by Django 5.0.2 on 2024-04-17 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0013_jobapplication_jaconstraint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="overview",
        ),
    ]
