# Generated by Django 5.0.2 on 2024-04-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_questionresult'),
    ]

    database_operations = [
        migrations.AlterModelTable('QuestionResult', 'questionnaire_questionresult'),
    ]

    state_operations = [
        migrations.DeleteModel('QuestionResult'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(database_operations, state_operations),
    ]
