# Generated by Django 5.0.2 on 2024-04-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_delete_questionresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'job', 'verbose_name_plural': 'jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name': 'job application', 'verbose_name_plural': 'job applications'},
        ),
        migrations.AlterModelOptions(
            name='jobbookmark',
            options={'verbose_name': 'job bookmark', 'verbose_name_plural': 'job bookmarks'},
        ),
    ]
