# Generated by Django 5.0.2 on 2024-03-20 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_job_alter_company_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name="JobBookMarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jobid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.job"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
