# Generated by Django 5.0.2 on 2024-03-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_options_user_company_user_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(blank=True, max_length=150, verbose_name='interest'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.CharField(blank=True, max_length=150, verbose_name='skill'),
        ),
    ]
