# Generated by Django 5.0.2 on 2024-03-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_interest_user_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=150, verbose_name='job_name')),
                ('degree', models.BooleanField(default=False)),
                ('personality_type', models.JSONField(default=dict)),
                ('holland_code', models.JSONField(default=dict)),
                ('education_one', models.JSONField(default=dict)),
                ('education_two', models.JSONField(default=dict)),
                ('education_three', models.JSONField(default=dict)),
            ],
        ),
    ]
