# Generated by Django 5.0.2 on 2024-03-20 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_job_description_jobbookmarks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobbookmarks",
            old_name="jobid",
            new_name="job",
        ),
    ]
