# Generated by Django 5.0.2 on 2024-03-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_holland_code_personality_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='user_pdfs/'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='education_three',
            field=models.CharField(blank=True, max_length=150, verbose_name='education_three'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='education_two',
            field=models.CharField(blank=True, max_length=150, verbose_name='education_two'),
        ),
    ]
