# Generated by Django 5.0.2 on 2024-03-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_jobbookmarks_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.CharField(
                default="https://media.glassdoor.com/sql/9079/google-squarelogo-1441130773284.png",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
