# Generated by Django 5.0.2 on 2024-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_jobs_holland_code_alter_user_resume_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='holland_code',
            field=models.ManyToManyField(blank=True, to='core.holland_code'),
        ),
    ]
