# Generated by Django 5.0.2 on 2024-03-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_jobbookmarks_job_remove_jobbookmarks_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('attempts', models.IntegerField(default=1)),
            ],
        ),
    ]
