# Generated by Django 5.0.2 on 2024-03-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_questionare_question_mbti'),
    ]

    operations = [
        migrations.CreateModel(
            name='interest_holland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question_holland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('choices', models.ManyToManyField(blank=True, to='core.interest_holland')),
            ],
        ),
    ]
