# Generated by Django 5.0.2 on 2024-04-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_failedlogin'),
        ('core', '0012_rename_question_fix_question_mbti_question'),
    ]

    operations = [
    ]
