# Generated by Django 5.0.2 on 2024-04-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20240403_1023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='holland_code',
            new_name='HollandCode',
        ),
        migrations.RenameModel(
            old_name='personality_type',
            new_name='PersonalityType',
        ),
        migrations.RenameModel(
            old_name='Question_holland',
            new_name='QuestionHolland',
        ),
        migrations.RenameModel(
            old_name='interest_holland',
            new_name='QuestionHollandInterest',
        ),
        migrations.RenameModel(
            old_name='Question_MBTI',
            new_name='QuestionMBTI',
        ),
    ]
