# Generated by Django 5.0.2 on 2024-04-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_holland_code_hollandcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituion', models.CharField(max_length=100, unique=True)),
                ('duration', models.CharField(max_length=10)),
                ('degree', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='institution',
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.ManyToManyField(blank=True, to='core.education'),
        ),
    ]
