# Generated by Django 5.0.2 on 2024-04-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20240403_1230'),
        ('core', '0014_rename_holland_code_hollandcode_and_more'),
    ]

    operations = [
    ]
