# Generated by Django 5.0.2 on 2024-04-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_education_remove_user_degree_remove_user_institution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='degree',
            new_name='_degree',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='duration',
            new_name='_duration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.JSONField(default='', verbose_name='Education'),
        ),
    ]
