# Generated by Django 5.0.2 on 2024-04-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_degree_education__degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.JSONField(default=dict, verbose_name='Education'),
        ),
    ]
