# Generated by Django 5.0.2 on 2024-04-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20240403_1331'),
        ('core', '0019_contact_work_experience_remove_user_company_and_more'),
    ]

    operations = [
    ]
