# Generated by Django 5.0.2 on 2024-04-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contact_work_experience_remove_user_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='others',
            field=models.CharField(blank=True, max_length=1000, verbose_name='others'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.JSONField(blank=True, default=list, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.JSONField(blank=True, default=list, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_experience',
            field=models.JSONField(blank=True, default=list, verbose_name='Work_Experience'),
        ),
    ]
