# Generated by Django 5.0.2 on 2024-04-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20240407_1624'),
        ('core', '0020_user_others_alter_user_contact_alter_user_education_and_more'),
    ]

    operations = [
    ]
