# Generated by Django 5.0.2 on 2024-04-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_others_alter_user_contact_alter_user_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='_degree',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='work_experience',
            old_name='_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='work_experience',
            old_name='_position',
            new_name='position',
        ),
    ]
