# Generated by Django 5.0.2 on 2024-04-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20240409_1139'),
        ('core', '0021_rename__address_contact_address_and_more'),
    ]

    operations = [
    ]
