# Generated by Django 5.0.2 on 2024-04-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_delete_contact_delete_education_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
