# Generated by Django 5.0.2 on 2024-04-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_jobs_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionHolland',
            new_name='HollandCodeQuestion',
        ),
        migrations.RenameModel(
            old_name='QuestionHollandInterest',
            new_name='HollandCodeQuestionInterest',
        ),
        migrations.RenameModel(
            old_name='QuestionMBTI',
            new_name='MBTIQuestion',
        ),
        migrations.AlterModelOptions(
            name='mbtiquestion',
            options={'verbose_name_plural': 'MBTI Questions'},
        ),
    ]
