# Generated by Django 5.0.2 on 2024-04-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_questionholland_hollandcodequestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.TextField(blank=True, verbose_name='interest'),
        ),
        migrations.AlterField(
            model_name='user',
            name='others',
            field=models.TextField(blank=True, verbose_name='others'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.TextField(blank=True, verbose_name='skill'),
        ),
    ]
