# Generated by Django 5.0.2 on 2024-04-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_20240410_1449'),
        ('core', '0025_alter_user_interest_alter_user_others_and_more'),
    ]

    operations = [
    ]
