# Generated by Django 5.0.2 on 2024-04-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_questionresult_alter_user_resume_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresult',
            name='Question_username',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='MbtiType',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='category_one',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='category_three',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='category_two',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='codeOne',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='codeTwo',
            field=models.CharField(default='', max_length=250),
        ),
    ]
