# Generated by Django 5.0.2 on 2024-04-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20240411_1619'),
        ('core', '0027_questionresult_question_username_and_more'),
    ]

    operations = [
    ]
