# Generated by Django 5.0.2 on 2024-04-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_questionresult_question_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresult',
            name='codeTwo',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
