# Generated by Django 5.0.2 on 2024-04-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_questionresult_codetwo'),
        ('core', '0028_merge_20240412_1343'),
    ]

    operations = [
    ]
