# Generated by Django 5.0.2 on 2024-04-15 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_questionresult_codetwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complete_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
