# Generated by Django 5.0.2 on 2024-04-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_merge_20240415_1454'),
        ('core', '0029_user_complete_question_user_mentor'),
    ]

    operations = [
    ]
