# Generated by Django 5.0.2 on 2024-04-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_user_complete_question_user_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_jobseeker',
            field=models.BooleanField(default=True),
        ),
    ]
