# Generated by Django 5.0.2 on 2024-04-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_user_is_jobseeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='long_goal',
            field=models.TextField(blank=True, verbose_name='long_goal'),
        ),
        migrations.AddField(
            model_name='user',
            name='short_goal',
            field=models.TextField(blank=True, verbose_name='short_goal'),
        ),
    ]
