# Generated by Django 5.0.2 on 2024-04-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_user_is_jobseeker'),
        ('core', '0030_merge_20240415_1545'),
    ]

    operations = [
    ]
