# Generated by Django 5.0.2 on 2024-04-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_merge_20240417_1157'),
        ('core', '0031_user_long_goal_user_motivation_user_short_goal'),
    ]

    operations = [
    ]
