# Generated by Django 5.0.2 on 2024-04-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20240417_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='motivation1',
            field=models.TextField(blank=True, verbose_name='motivation1'),
        ),
        migrations.AddField(
            model_name='user',
            name='motivation2',
            field=models.TextField(blank=True, verbose_name='motivation2'),
        ),
        migrations.AddField(
            model_name='user',
            name='motivation3',
            field=models.TextField(blank=True, verbose_name='motivation3'),
        ),
    ]
