# Generated by Django 5.0.2 on 2024-04-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_tips_user_motivation1_user_motivation2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='motivation2',
        ),
        migrations.AddField(
            model_name='user',
            name='t2',
            field=models.TextField(blank=True, verbose_name='motivation2'),
        ),
    ]
