# Generated by Django 5.0.2 on 2024-04-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_user_motivation2_user_t2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='t2',
            new_name='motivation2',
        ),
    ]
