# Generated by Django 5.0.2 on 2024-04-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_t2_user_motivation2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee', models.CharField(blank=True, max_length=100, null=True, verbose_name='mentee')),
                ('mentor', models.CharField(blank=True, max_length=100, null=True, verbose_name='mentor')),
                ('instruction', models.TextField(blank=True, verbose_name='instruction')),
                ('complete', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
            ],
        ),
    ]
