# Generated by Django 5.0.2 on 2024-04-17 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mentee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentee_feedback_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentor_feedback_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
