# Generated by Django 5.0.2 on 2024-04-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_feedback_mentee_alter_feedback_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='mentor',
        ),
    ]
