# Generated by Django 5.0.2 on 2024-04-18 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_remove_feedback_mentor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuestionResult",
        ),
    ]
