# Generated by Django 5.0.2 on 2024-04-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_delete_questionresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='holland_code',
        ),
        migrations.RemoveField(
            model_name='hollandcodequestion',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='job',
            name='personality_type',
        ),
        migrations.DeleteModel(
            name='MBTIQuestion',
        ),
        migrations.DeleteModel(
            name='HollandCode',
        ),
        migrations.DeleteModel(
            name='HollandCodeQuestion',
        ),
        migrations.DeleteModel(
            name='HollandCodeQuestionInterest',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='PersonalityType',
        ),
    ]
