# Generated by Django 5.0.2 on 2024-04-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_job_holland_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tips',
            new_name='Tip',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='failedlogin',
            options={'verbose_name': 'failed login', 'verbose_name_plural': 'failed logins'},
        ),
        migrations.AlterModelOptions(
            name='tip',
            options={'verbose_name': 'tip', 'verbose_name_plural': 'tips'},
        ),
    ]
