# Generated by Django 5.0.2 on 2024-04-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_tips_tip_alter_company_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
