# Generated by Django 5.0.2 on 2024-04-19 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_set', to='core.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentee_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
