# Generated by Django 5.0.2 on 2024-04-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionresult',
            options={'verbose_name': 'question result', 'verbose_name_plural': 'question results'},
        ),
    ]
