# Generated by Django 5.0.2 on 2024-03-12 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_comment_created_at_comment_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ("created_at",)},
        ),
    ]
